<a href="https://colab.research.google.com/github/ab17254/dissertation/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://www.dropbox.com/s/jh40sd8xebjg9pn/ge_2017.sqlite.zip?dl=1

--2021-05-03 14:08:14--  https://www.dropbox.com/s/jh40sd8xebjg9pn/ge_2017.sqlite.zip?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.82.18, 2620:100:6032:18::a27d:5212
Connecting to www.dropbox.com (www.dropbox.com)|162.125.82.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/jh40sd8xebjg9pn/ge_2017.sqlite.zip [following]
--2021-05-03 14:08:15--  https://www.dropbox.com/s/dl/jh40sd8xebjg9pn/ge_2017.sqlite.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com/cd/0/get/BNwj2cLVjRPfaG7SJQYO5Iluwiwv3scVzfAdIHii8juFcsP8IgKJvLY38wWCjLa2aWnJ7s5y9A-rmGFSP2yhJingY1HWlWMassZpTCCFY4dRdqodQWSPOfT6qDSB93b62MD5BZKGYMx0nejDvxPy0PxR/file?dl=1# [following]
--2021-05-03 14:08:15--  https://ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com/cd/0/get/BNwj2cLVjRPfaG7SJQYO5Iluwiwv3scVzfAdIHii8juFcsP8IgKJvLY38wWCjLa2aWnJ7s5y9A-rmGFSP2yhJingY1HWlWMassZpTCCFY4dRdqodQWSPOfT6qDSB93b62MD5BZKGYMx0nejDvxPy0PxR/file?dl=1
Resolving ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com (ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com)... 162.125.82.15, 2620:100:6032:15::a27d:520f
Connecting to ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com (ucc57b94bdf014510f7772abac23.dl.dropboxusercontent.com)|162.125.82.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31772915 (30M) [application/binary]
Saving to: ‘ge_2017.sqlite.zip?dl=1’

ge_2017.sqlite.zip? 100%[===================>]  30.30M  12.7MB/s    in 2.4s

2021-05-03 14:08:18 (12.7 MB/s) - ‘ge_2017.sqlite.zip?dl=1’ saved [31772915/31772915]

In [2]:
!unzip /content/ge_2017.sqlite.zip?dl=1 \
-d /content/data

Archive:  /content/ge_2017.sqlite.zip?dl=1
  inflating: /content/data/ge_2017.sqlite
   creating: /content/data/__MACOSX/
  inflating: /content/data/__MACOSX/._ge_2017.sqlite

In [3]:
import pandas as pd
import sqlite3
import re
import numpy as np
import collections
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [4]:
con_ge2017 = sqlite3.connect('/content/data/ge_2017.sqlite')

In [8]:
df = pd.read_sql_query('''SELECT * FROM users''', con_ge2017)
df.shape

(91256, 19)

In [9]:
users = pd.read_sql_query('''SELECT *
FROM users
WHERE screen_name_in = "1" 
''', con_ge2017)

In [10]:
users

      verified             location  ... user_created_at_dt screen_name_in
0            0  Mostly in Liverpool  ...       1.233943e+09              1
1            0              Grimsby  ...       1.241954e+09              1
2            1  Edinburgh, Scotland  ...       1.401921e+09              1
3            0    Market Harborough  ...       1.418133e+09              1
4            0       Ealing, London  ...       1.299070e+09              1
...        ...                  ...  ...                ...            ...
1050         0                 None  ...       1.387750e+09              1
1051         0           Winchester  ...       1.379944e+09              1
1052         0     ollerton England  ...       1.409507e+09              1
1053         0       United Kingdom  ...       1.458056e+09              1
1054         0               London  ...       1.246297e+09              1

[1055 rows x 19 columns]

In [11]:
tweets = pd.read_sql_query('''SELECT *
FROM tweets AS a
INNER JOIN users AS b
ON a.user_id_str = b.user_id_str
WHERE b.screen_name_in = "1"
''', con_ge2017)

In [12]:
tweets.groupby(['screen_name']).count().sort_values(['doc_id'], ascending=False)

                 doc_id  text  ...  user_created_at_dt  screen_name_in
screen_name                    ...
DrTeckKhong         149   149  ...                 149             149
opgiftbox           146   146  ...                 146             146
stevebeasant        127   127  ...                 127             127
politicallynate     127   127  ...                 127             127
lynbrownmp           97    97  ...                  97              97
...                 ...   ...  ...                 ...             ...
cmartinLD             1     1  ...                   1               1
patrickloweukip       1     1  ...                   1               1
FlickD                1     1  ...                   1               1
FoysolChoudhury       1     1  ...                   1               1
MarkFieldUK           1     1  ...                   1               1

[1055 rows x 47 columns]

In [13]:
tweets

                                 doc_id  ... screen_name_in
0         tw_json_6_201705261745.json.1  ...              1
1       tw_json_6_201705261745.json.146  ...              1
2        tw_json_6_201705261745.json.51  ...              1
3       tw_json_6_201705261745.json.519  ...              1
4       tw_json_6_201705261745.json.568  ...              1
...                                 ...  ...            ...
12030  tw_json_6_201706080815.json.4681  ...              1
12031  tw_json_6_201706080815.json.4891  ...              1
12032  tw_json_6_201706080815.json.4965  ...              1
12033  tw_json_6_201706080815.json.5260  ...              1
12034  tw_json_6_201706080815.json.5442  ...              1

[12035 rows x 48 columns]

In [14]:
tweets.to_csv('/content/tweets.csv')